white_length_total: 6.0
white_height: 0.3
white_thick_bottom: 1.8
white_thin_bottom: 1.6

black_length_ratio: 0.5
black_height: 0.4
black_width: 0.8

space: 0.05
group_3_ratio: 0.3
group_4_ratio: 0.3
