white_length_total: 12.0
white_height: 3.0
white_thick_bottom: 2.2
white_thin_bottom: 2.2

black_length_ratio: 0.7
black_height: 3.7
black_width: 1.5

space: 0.2
group_3_ratio: 0.7
group_4_ratio: 0.7
